Upgrade outdated packages
* Leaving graphql at 14.7.0 instead of upgrading to v15.4.0 because the upgrade + `gatsby build` results in an error when building schema:

“Missing onError handler for invocation 'building-schema', error was 'TypeError: (0 , _buildASTSchema.getDescription) is not a function'. Stacktrace was 'TypeError: (0 , _buildASTSchema.getDescription) is not a function”